CREATE TABLE TASKSTATUS 
(
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR(50) UNIQUE NOT NULL,
	DESCRIPTION TEXT NOT NULL
);

CREATE TABLE EMPLOYEE 
(
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE TASK
(
	ID INTEGER PRIMARY KEY,
	TITLE VARCHAR(200) NOT NULL,
	NUMBER VARCHAR(20) UNIQUE NOT NULL,
	DESCRIPTION TEXT NOT NULL,	
	TASKSTATUSID INTEGER NOT NULL REFERENCES TASKSTATUS,
	APPROVED BOOLEAN,
	EXECUTOR INTEGER REFERENCES EMPLOYEE	
);

CREATE TABLE USERTABLE
(
	USERID VARCHAR(10) PRIMARY KEY, 
	EMPLOYEEID INTEGER REFERENCES EMPLOYEE UNIQUE,
	PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE GROUPTABLE
(
	USERID VARCHAR(10) NOT NULL REFERENCES USERTABLE, 
	GROUPID VARCHAR(20) NOT NULL, 
	PRIMARY KEY (USERID, GROUPID)
);

CREATE TABLE PRIMARY_KEY_SEQUENCES
(	
	TABLE_NAME VARCHAR(50) NOT NULL UNIQUE,
	CURRENT_PK_VALUE INTEGER NOT NULL
);

INSERT INTO PRIMARY_KEY_SEQUENCES (TABLE_NAME, CURRENT_PK_VALUE) VALUES ('TASKSTATUS', 0);
INSERT INTO PRIMARY_KEY_SEQUENCES (TABLE_NAME, CURRENT_PK_VALUE) VALUES ('EMPLOYEE', 0);
INSERT INTO PRIMARY_KEY_SEQUENCES (TABLE_NAME, CURRENT_PK_VALUE) VALUES ('TASK', 0);
