CREATE TABLE USERTABLE
(
	USERID VARCHAR(10) PRIMARY KEY, 
	EMPLOYEEID INTEGER REFERENCES EMPLOYEE UNIQUE,
	PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE GROUPTABLE
(
	USERID VARCHAR(10) NOT NULL REFERENCES USERTABLE, 
	GROUPID VARCHAR(20) NOT NULL, 
	PRIMARY KEY (USERID, GROUPID)
);
